- name: configuring user component
  hosts: user
  become: true
  tasks:
  - name: Disable default nodejs version
    ansible.builtin.command: "dnf module disable nodejs -y"

  - name: Enable specific nodejs version
    ansible.builtin.command: "dnf module enable nodejs:20 -y"

  - name: Installing nodejs
    ansible.builtin.dnf:
     name: nodejs
     state: present
  
  - name: Create a App directory 
    ansible.builtin.file:
     path: /app
     state: directory

  - name: Create system user
    ansible.builtin.user:
     name: roboshop
     shell: /sbin/nologin
     system: true
     home: /app

  - name: Download the code
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
     dest: /tmp/user.zip

  - name: Unzipping the zip file
    ansible.builtin.unarchive:
     src: /tmp/user.zip
     dest: /app
     remote_src: yes

  - name: Installing dependencies 
    community.general.npm:
     name: package.json
     path: /app

  - name: Creating user service
    ansible.builtin.copy:
     src: user.service
     dest: /etc/systemd/system/user.service

  - name: systemd reload
    ansible.builtin.systemd_service:
     daemon_reload: true

  - name: Starting and Enable user service
    ansible.builtin.service:
     name: user
     state: started
     enabled: yes